#!/bin/bash
BASECID="00000001008766A39D091E82DCB8"

while true; do
    clear
    echo "CIDgen by EMR"
    for i in {1..20}; do
        echo "$BASECID$(printf "%04d" $((RANDOM % 10000)))"
    done
    echo "--------------------------------"
    echo "Generated CIDs"
    read -rsn1
done